### PR TITLE
add versions command

### PR DESCRIPTION
**Pull request by BlackCoyote**
cuz fuk u

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
Why is that all on one line? Gross that line is way too long :(

**Comment by BlackCoyote** [comment]
deal with it

**Comment by mcmonkey4eva** [comment]
Dealt with.

**Comment by BlackCoyote** [comment]
this is why we can't have nice things </3 but srsly add something like this okay cause the amount of times i had to google this is too high

**Pull request closed without merging**
